export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SAVE_USER_SUCCESS = 'SAVE_USERS_SUCCESS';
export const SAVE_USER_FAILURE = 'SAVE_USERS_FAILURE';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const SET_USER = 'SET_USER';

export const REMOVE_USER = 'REMOVE_USER';

export const LOADING = 'LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

export const SORT_USERS = 'SORT_USERS';
